version: "3.8"

services:
  redpanda-1:
    image: redpandadata/redpanda:v23.2.15
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp=1
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=1
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr=PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr=PLAINTEXT://redpanda-1:28082,OUTSIDE://localhost:8082
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda-1:33145
    environment:
      REDPANDA_ADMIN_API_ADDRESS: "0.0.0.0:9644"
      REDPANDA_SEED_SERVERS: "redpanda-1:33145"
      REDPANDA_EMPTY_SEED_START: "true"
    ports:
      - "9092:9092"
      - "8082:8082"
      - "9644:9644"
      - "33145:33145"  # Expose RPC port
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9644/v1/status/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [datamasterylab]

  redpanda-2:
    image: redpandadata/redpanda:v23.2.15
    container_name: redpanda-2
    command:
      - redpanda
      - start
      - --smp=1
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=2
      - --seeds=redpanda-1:33145
      - --kafka-addr=PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr=PLAINTEXT://redpanda-2:29093,OUTSIDE://localhost:9093
      - --pandaproxy-addr=PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
      - --advertise-pandaproxy-addr=PLAINTEXT://redpanda-2:28083,OUTSIDE://localhost:8083
      - --rpc-addr=0.0.0.0:33146
      - --advertise-rpc-addr=redpanda-2:33146
    environment:
      REDPANDA_ADMIN_API_ADDRESS: "0.0.0.0:9645"
      REDPANDA_SEED_SERVERS: "redpanda-1:33145"
    ports:
      - "9093:9093"
      - "8083:8083"
      - "9645:9645"
      - "33146:33146"  # Expose RPC port
    healthcheck:
      test: ["CMD-SHELL", "sleep 30 && curl -f http://localhost:9645/v1/status/ready || exit 1"]
      interval: 15s
      timeout: 30s
      start_period: 60s
      retries: 10
    depends_on:
      redpanda-1:
        condition: service_healthy
    networks: [datamasterylab]

  redpanda-console:
    image: redpandadata/console:v2.3.1
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: "redpanda-1:29092,redpanda-2:29093"
      REDPANDA_ADMIN_API_ENABLED: "true"
      REDPANDA_ADMIN_API_URLS: "http://redpanda-1:9644,http://redpanda-2:9645"
    ports:
      - "8080:8080"
    depends_on:
      redpanda-1:
        condition: service_healthy
      redpanda-2:
        condition: service_healthy
    networks: [datamasterylab]

  jobmanager:
    image: flink:1.17.1
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    networks: [datamasterylab]

  taskmanager:
    image: flink:1.17.1
    container_name: taskmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - jobmanager
    networks: [datamasterylab]

  sql-client:
    image: flink:1.17.1
    container_name: sql-client
    command: > 
      /bin/bash -c "
      apt-get update && 
      apt-get install -y netcat-openbsd --no-install-recommends && 
      while ! nc -z jobmanager 8081; do 
        echo 'Waiting for JobManager...'; 
        sleep 1; 
      done; 
      /opt/flink/bin/sql-client.sh"
    depends_on:
      - jobmanager
    networks: [datamasterylab]

networks:
  datamasterylab:
    driver: bridge